name: Test ESLint

on:
  - pull_request

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0

      # Install your dependencies
      - run: npm ci

      # Run ESLint
      - run: yarn lint
